[project]
name = "database-ai-agents"
version = "0.0.1"
description = "AI Agents for Database interaction"
requires-python = "==3.13.5"
dependencies = [
  "langchain>=1.2.0",
  "requests>=2.32.5",
  "langchain-community>=0.4.1",
  "rich>=14.2.0",
  "langgraph>=1.0.5",
  "ipython>=9.8.0",
  "langchain-openai>=1.1.3",
  "pyodbc>=5.3.0",
  "python-dateutil>=2.9.0.post0",
  "fastapi>=0.124.4",
  "uvicorn>=0.38.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.notes]
description = "uvicorn main:app --reload"